services:
#  mysql:
#    image: 'mysql:latest'
#    environment:
#      - 'MYSQL_DATABASE=jdbc:mysql://143.106.241.4:3306/cl203334'
#      - 'MYSQL_PASSWORD=cl*203334'
#      - 'MYSQL_ROOT_PASSWORD=verysecret'
#      - 'MYSQL_USER=cl203334'
#    ports:
#      - '3306'
  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11434'
