package com.example.FullAPIdemo.ai.control;


import com.example.FullAPIdemo.ai.model.ChatRequest;
import com.example.FullAPIdemo.ai.model.Chat;
import com.example.FullAPIdemo.ai.model.Message;
import com.example.FullAPIdemo.database.model.User;
import com.example.FullAPIdemo.ai.repository.ChatRepository;
import com.example.FullAPIdemo.ai.repository.MessageRepository;
import com.example.FullAPIdemo.database.repository.UserRepository;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.chat.client.advisor.MessageChatMemoryAdvisor;
import org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor;
import org.springframework.ai.chat.memory.ChatMemory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpHeaders;
import org.springframework.http.ResponseCookie;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import reactor.core.publisher.Flux;
import tools.jackson.databind.ObjectMapper;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.time.LocalDateTime;
import java.util.*;

@RestController
@RequestMapping("/apiOllama")
public class OllamaController {
    @Autowired
    private UserRepository uRepo;

    @Autowired
    private ChatRepository cRepo;

    @Autowired
    private MessageRepository mRepo;

    private final ChatClient chatClient;

    public OllamaController(ChatClient.Builder builder, ChatMemory chatMemory){

        this.chatClient = builder
                .defaultSystem("Voce é uma IA de assostente nutricional")
                .defaultAdvisors(
                        MessageChatMemoryAdvisor.builder(chatMemory).build(),
                        new SimpleLoggerAdvisor()
                )
                .build();
    }

    @GetMapping("/ollama")
    public Flux<String> ollama(){
        return chatClient.prompt().
                user("how many calories are there in one strawberry").
                stream().
                content();
    }

    @PostMapping("/chat/messages")
    public ResponseEntity<String> listChat(@RequestBody @Valid ChatRequest chatRequest){
        ArrayList<Message> list = mRepo.findByChatIdOrderByCreatedAtAsc(chatRequest.getChatId());


        for(Message m : list){
            //list.add(m.getContent());
            System.out.println(m.getContent());
        }

        ObjectMapper mapper = new ObjectMapper();
        String jsonList = mapper.writeValueAsString(list);

        System.out.println(jsonList);

        return ResponseEntity.ok().body(jsonList);
    }

    @PostMapping("/chatlist")
    public ResponseEntity<String> listUserChats(@RequestBody @Valid ChatRequest chatRequest){
        ArrayList<Chat> list = cRepo.findByUserId(chatRequest.getChatId());

        ObjectMapper mapper = new ObjectMapper();
        String jsonList = mapper.writeValueAsString(list);

        System.out.println(jsonList);

        return ResponseEntity.ok().body(jsonList);
    }

    @PostMapping("/chat")
    public ResponseEntity<Output> newChat(@RequestBody @Valid ChatRequest chatRequest){
        String username = chatRequest.getUsername();
        String prompt = chatRequest.getPrompt();
        Long chatId = chatRequest.getChatId();
        LocalDateTime time = LocalDateTime.now();

        List<User> userList = this.uRepo.findByUsernameIs(chatRequest.getUsername());
            try {
                User u = userList.getFirst();
                if(chatId == null) {
                    Chat chat = new Chat();
                    chat.setUser(u);
                    cRepo.save(chat); //saves the chat with an autogenerated id
                    Message msg = new Message();
                    msg.setCreatedAt(time);
                    msg.setChat(chat);
                    msg.setContent(prompt);
                    mRepo.save(msg);

                    var response = this.chatClient.prompt().
                            user(msg.getContent()).
                            advisors(a -> a.param(ChatMemory.CONVERSATION_ID, chat.getId())).
                            call().
                            content();

                    System.out.println("finished generation\nresponse:\n\n" + response);

                    Message res = new Message();
                    res.setCreatedAt(time);
                    res.setChat(chat);
                    res.setRole("ASSISTANT");
                    res.setContent(response);
                    mRepo.save(msg);

                    Output output = new Output(response);

                    return ResponseEntity.ok().body(output);
                } else {
                    Chat chat = cRepo.getReferenceById(chatId);
                    Message msg = new Message();
                    msg.setCreatedAt(time);
                    msg.setChat(chat);
                    msg.setContent(prompt);
                    mRepo.save(msg);

                    var response = this.chatClient.prompt().
                            user(msg.getContent()).
                            advisors(a -> a.param(ChatMemory.CONVERSATION_ID, chat.getId())).
                            call().
                            content();

                    System.out.println("finished generation\nresponse:\n\n" + response);

                    Output output = new Output(response);

                    return ResponseEntity.ok().body(output);
                }

            } catch (NoSuchElementException e) {
                System.out.printf("Username doesn't exist");
                return ResponseEntity.ok(new Output("username errorrr"));
            }
    }

    @PostMapping("/prompt")
    public ResponseEntity<Output> ollamaPrompt(@RequestBody @Valid Input input, @CookieValue (name = "X-CONV-ID", required = false) String convId){

        String conversationId = convId == null ? UUID.randomUUID().toString() : convId;
        System.out.println("generating...");

        var response = this.chatClient.prompt().
                user(input.prompt()).
                advisors(a -> a.param(ChatMemory.CONVERSATION_ID, conversationId)).
                call().
                content();

        ResponseCookie cookie = ResponseCookie.from("X-CONV-ID", conversationId)
                .path("/")
                .maxAge(3600)
                .build();

        System.out.println("finished generation\nresponse:\n\n" + response);

        Output output = new Output(response);

        return ResponseEntity.ok().header(HttpHeaders.SET_COOKIE, cookie.toString()).body(output);
    }

    record Input(@NotNull String prompt){}
    record Output(String content) {}


}
