spring.application.name=FullAPIdemo

#Ollama
spring.ai.ollama.chat.model=deepseek-r1:1.5b

#MySql

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://143.106.241.4:3306/cl203334
spring.datasource.username=cl203334
spring.datasource.password=cl*22042008
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.data.jpa.repositories.enabled=true
spring.jpa.database=mysql
